In [24]:
import pandas as pd
import numpy as np

In [25]:
df = pd.read_csv('data/be_subscribers_auto_recurring.csv')
df.head()

,Login ID (SSO ID),Master Account ID,Invoice,Subaccount ID,Cardholder Name,Monexa Order #,Plan,Last Charge Date,Nex Renewal Date,Charge Status,...,Address 1,Address 2,City,State/Province,Country,Postal/Zip,Phone #,Other,AS Order #,Serial #
0,4252395,3961477,12 Month Service ActivePerl Business Edition,3961478,Adam Estabrook,7e90ad42bcf9da691cb81dbfa48c7cb13f7abb84,ActiveState Services,9/5/2017,9/5/2018,successful,...,550 Cochituate Rd,NaN,Framingham,Massachusetts,United States,01701,5086631050,NaN,601426,S834EA785951
1,4252395,3961477,12 Month Service ActivePerl Business Edition,3961479,Adam Estabrook,1f0760c6353f0edc06e5cd96c65036da22e710b9,ActiveState Services,9/5/2017,9/5/2018,successful,...,550 Cochituate Rd,NaN,Framingham,Massachusetts,United States,01701,5086631050,NaN,601426,S0A7A3C0AADD
2,905827,40837,12 Month Service ActivePerl Business Edition,3301729,Pete Griffiths,33ac6d3b969836ac9f9d085c9de85818cde61dc9,ActiveState Services,9/11/2017,9/11/2018,successful,...,Park Crescent,NaN,Peterborough,NaN,United Kingdom,PE1 4DZ,441733762326,NaN,601465,S2E9CD0F5945
3,4215377,117540,12 Month Service ActivePython Business Edition,961092,Robert N Husted,a1702f5a734ac8d9e5b1792fa5f14c30f5801821,ActiveState Services,9/27/2017,9/27/2018,successful,...,80 Maiden Lane,NaN,New York,New York,United States,10038,2122331250,NaN,601806,S04E031E11C4
4,4234590,1942458,12 Month Service ActivePerl Business Edition,5845308,Lezlie Zupan,f37330ccb4ed2570bfa1c7275e27dec8b487de08,ActiveState Services,10/4/2017,10/4/2018,successful,...,"801, 18th Street NW",NaN,Washington,District of Columbia,United States,20006,2024167755,NaN,601955,S0F8199A8494

In [26]:
df.columns

Index(['Login ID (SSO ID)', 'Master Account ID', 'Invoice', 'Subaccount ID',
       'Cardholder Name', 'Monexa Order #', 'Plan', 'Last Charge Date',
       'Nex Renewal Date', 'Charge Status', 'Account Status',
       'Service Enabled', 'Amount', 'E-mail', 'Company Name', 'Address 1',
       'Address 2', 'City', 'State/Province', 'Country', 'Postal/Zip',
       'Phone #', 'Other', 'AS Order #', 'Serial #'],
      dtype='object')

In [27]:
df = df[['Login ID (SSO ID)', 'Invoice',
       'Cardholder Name', 'Last Charge Date',
       'Nex Renewal Date', 'Service Enabled', 
       'Amount', 'E-mail', 'Company Name', 'AS Order #', 'Serial #']]

In [28]:
df.head()

,Login ID (SSO ID),Invoice,Cardholder Name,Last Charge Date,Nex Renewal Date,Service Enabled,Amount,E-mail,Company Name,AS Order #,Serial #
0,4252395,12 Month Service ActivePerl Business Edition,Adam Estabrook,9/5/2017,9/5/2018,ActivePerl Business Edition,999,sysadmin@plurisinc.com,Pluris Marketing,601426,S834EA785951
1,4252395,12 Month Service ActivePerl Business Edition,Adam Estabrook,9/5/2017,9/5/2018,ActivePerl Business Edition,999,sysadmin@plurisinc.com,Pluris Marketing,601426,S0A7A3C0AADD
2,905827,12 Month Service ActivePerl Business Edition,Pete Griffiths,9/11/2017,9/11/2018,ActivePerl Business Edition,999,network.services@peterborough.ac.uk,Peterborough Regional College,601465,S2E9CD0F5945
3,4215377,12 Month Service ActivePython Business Edition,Robert N Husted,9/27/2017,9/27/2018,ActivePython Business Edition,999,bob.husted@miacanalytics.com,MIAC,601806,S04E031E11C4
4,4234590,12 Month Service ActivePerl Business Edition,Lezlie Zupan,10/4/2017,10/4/2018,ActivePerl Business Edition,999,lesliez@pva.org,PVA,601955,S0F8199A8494

In [31]:
pd.pivot_table(df, index=['Company Name', 'Login ID (SSO ID)'])

                                                        AS Order #  Amount
Company Name                         Login ID (SSO ID)
All for One Steeb AG                 4246428              603222.0     999
Aquent                               4226892              602889.0     999
Banco Popular EspaÃ±ol S.A.           4269849              603229.0     999
Barrachd Limited                     4257650              603076.0     999
Brother International (Aust) Pty Ltd 4257316              603018.0     999
COOP Genossenschaft                  591733               603434.0     999
Data Conversion Laboratory Inc.      157691               603935.0     999
Dbvisit Software Limited             4246907              603869.0     999
Deceuninck NV                        4267476              602021.0     999
FibreBlu Technology Inc.             4285914              604454.0     399
Fides Management                     359317               604138.0     999
Fiserv                               4285462              604249.0     999
G-C Partners                         784231               603630.0     999
Grain Corp.                          938287               604321.0     999
Green River College                  4265223              604617.0     999
Inasys GmbH                          4263974              604322.0     999
Levi, Ray & Shoup, Inc.              4272502              604472.0     999
MIAC                                 4215377              601806.0     999
Macmillan Publishers                 4247919              603823.0     999
Merck                                4278878              603691.0    1200
Michelin                             4282703              603950.0     999
Migros ZÃ¼rich                        4193856              602912.0     999
Morneau Shepell ltd                  4285717              604368.0     999
NCCW                                 4241871              603975.5     999
Overnite Software Inc.               4281667              603846.0     999
PVA                                  4234590              601955.0     999
Parker-Hannifin Corporation          4284735              604015.0     999
Peterborough Regional College        905827               601465.0     999
Pluris Marketing                     4252395              601426.0     999
Princeton University                 287871               603756.0     999
Samba Plans                          4221090              604293.0     999
Skagit Valley College                4248660              604006.0     999
Summit IT solutions Pvt Ltd.         4203507              602805.0    1200
Taylor Corporation                   4270182              603179.0     999
Traquer Oy                           4185057              603265.0     999
Trepp, LLC                           4276870              602609.0    1200

In [19]:
ucompanies = df['Company Name'].unique()
len(ucompanies)

36

In [13]:
# grouping columns: Company Name Cardholder name
# aggregating column: Amount
# aggregating function: sum
df.groupby(['Company Name', 'Cardholder Name']).agg({'Amount': 'sum'})
# flights.groupby(['AIRLINE', 'WEEKDAY']).agg({'CANCELLED': 'sum'}).head(7)

                                                         Amount
Company Name                         Cardholder Name
All for One Steeb AG                 Cindy Schneider        999
Aquent                               Robert Stretz          999
Banco Popular EspaÃ±ol S.A.           Marcos Hernandez       999
Barrachd Limited                     clark wilson          1998
Brother International (Aust) Pty Ltd Terence Yuen           999
COOP Genossenschaft                  Christian Mueller      999
Data Conversion Laboratory Inc.      Judy Gross             999
Dbvisit Software Limited             Anton Els              999
Deceuninck NV                        Tec support            999
FibreBlu Technology Inc.             Kirk Pollock           399
Fides Management                     Maarten Van Laere      999
Fiserv                               Jerry Rabenberg        999
G-C Partners                         David Cowen            999
Grain Corp.                          Klaus Brinkmeyer       999
Green River College                  Rhonda Daulton         999
Inasys GmbH                          Suzanne Johnston       999
Levi, Ray & Shoup, Inc.              John Runions           999
MIAC                                 Robert N Husted        999
Macmillan Publishers                 Mariano Gardellini    1998
Merck                                Daniel Arnost         1200
Michelin                             William Rhoten         999
Migros ZÃ¼rich                        Richard Huber         1998
Morneau Shepell ltd                  Morneau Shepell       2997
NCCW                                 Theo Ariens           3996
Overnite Software Inc.               Ernest Bowie           999
PVA                                  Lezlie Zupan           999
Parker-Hannifin Corporation          Robert Deragisch       999
Peterborough Regional College        Pete Griffiths         999
Pluris Marketing                     Adam Estabrook        1998
Princeton University                 Steven Niedzwiecki     999
Samba Plans                          Pat Peel               999
Skagit Valley College                Teresa Miller          999
Summit IT solutions Pvt Ltd.         Vasudev Nayak         1200
Taylor Corporation                   Deven McVenes          999
Traquer Oy                           Sami Maenpaa           999
Trepp, LLC                           David Baboo           1200

In [23]:
pd.pivot_table(df, index=['Company Name'])
# mylist = .pivot(index='Company Name', columns='Cardholder Name', values='Amount')
# mylist

                                      AS Order #  Amount  Login ID (SSO ID)
Company Name
All for One Steeb AG                    603222.0     999            4246428
Aquent                                  602889.0     999            4226892
Banco Popular EspaÃ±ol S.A.              603229.0     999            4269849
Barrachd Limited                        603076.0     999            4257650
Brother International (Aust) Pty Ltd    603018.0     999            4257316
COOP Genossenschaft                     603434.0     999             591733
Data Conversion Laboratory Inc.         603935.0     999             157691
Dbvisit Software Limited                603869.0     999            4246907
Deceuninck NV                           602021.0     999            4267476
FibreBlu Technology Inc.                604454.0     399            4285914
Fides Management                        604138.0     999             359317
Fiserv                                  604249.0     999            4285462
G-C Partners                            603630.0     999             784231
Grain Corp.                             604321.0     999             938287
Green River College                     604617.0     999            4265223
Inasys GmbH                             604322.0     999            4263974
Levi, Ray & Shoup, Inc.                 604472.0     999            4272502
MIAC                                    601806.0     999            4215377
Macmillan Publishers                    603823.0     999            4247919
Merck                                   603691.0    1200            4278878
Michelin                                603950.0     999            4282703
Migros ZÃ¼rich                           602912.0     999            4193856
Morneau Shepell ltd                     604368.0     999            4285717
NCCW                                    603975.5     999            4241871
Overnite Software Inc.                  603846.0     999            4281667
PVA                                     601955.0     999            4234590
Parker-Hannifin Corporation             604015.0     999            4284735
Peterborough Regional College           601465.0     999             905827
Pluris Marketing                        601426.0     999            4252395
Princeton University                    603756.0     999             287871
Samba Plans                             604293.0     999            4221090
Skagit Valley College                   604006.0     999            4248660
Summit IT solutions Pvt Ltd.            602805.0    1200            4203507
Taylor Corporation                      603179.0     999            4270182
Traquer Oy                              603265.0     999            4185057
Trepp, LLC                              602609.0    1200            4276870

In [36]:
df2 = pd.read_csv('data/be_subscribers_auto_recurring.csv')
df2.head()

,Login ID (SSO ID),Master Account ID,Invoice,Subaccount ID,Cardholder Name,Monexa Order #,Plan,Last Charge Date,Nex Renewal Date,Charge Status,...,Address 1,Address 2,City,State/Province,Country,Postal/Zip,Phone #,Other,AS Order #,Serial #
0,4252395,3961477,12 Month Service ActivePerl Business Edition,3961478,Adam Estabrook,7e90ad42bcf9da691cb81dbfa48c7cb13f7abb84,ActiveState Services,9/5/2017,9/5/2018,successful,...,550 Cochituate Rd,NaN,Framingham,Massachusetts,United States,01701,5086631050,NaN,601426,S834EA785951
1,4252395,3961477,12 Month Service ActivePerl Business Edition,3961479,Adam Estabrook,1f0760c6353f0edc06e5cd96c65036da22e710b9,ActiveState Services,9/5/2017,9/5/2018,successful,...,550 Cochituate Rd,NaN,Framingham,Massachusetts,United States,01701,5086631050,NaN,601426,S0A7A3C0AADD
2,905827,40837,12 Month Service ActivePerl Business Edition,3301729,Pete Griffiths,33ac6d3b969836ac9f9d085c9de85818cde61dc9,ActiveState Services,9/11/2017,9/11/2018,successful,...,Park Crescent,NaN,Peterborough,NaN,United Kingdom,PE1 4DZ,441733762326,NaN,601465,S2E9CD0F5945
3,4215377,117540,12 Month Service ActivePython Business Edition,961092,Robert N Husted,a1702f5a734ac8d9e5b1792fa5f14c30f5801821,ActiveState Services,9/27/2017,9/27/2018,successful,...,80 Maiden Lane,NaN,New York,New York,United States,10038,2122331250,NaN,601806,S04E031E11C4
4,4234590,1942458,12 Month Service ActivePerl Business Edition,5845308,Lezlie Zupan,f37330ccb4ed2570bfa1c7275e27dec8b487de08,ActiveState Services,10/4/2017,10/4/2018,successful,...,"801, 18th Street NW",NaN,Washington,District of Columbia,United States,20006,2024167755,NaN,601955,S0F8199A8494

In [37]:
df3 = df2[['Login ID (SSO ID)', 'Invoice',
       'Cardholder Name', 'Last Charge Date',
       'Nex Renewal Date', 'Service Enabled', 
       'Amount', 'E-mail', 'Company Name', 'AS Order #', 'Serial #']]

In [65]:
pd.pivot_table(df3, index=['Company Name', 'Cardholder Name', 'E-mail', 'Service Enabled', 'Serial Number'], values=['Amount'],aggfunc=[np.sum], margins=True)

KeyError: 'Serial Number'

In [55]:
df4 = df3[['Company Name', 'Cardholder Name', 'E-mail', 'Serial #', 'Amount']]
df4

,Company Name,Cardholder Name,E-mail,Serial #,Amount
0,Pluris Marketing,Adam Estabrook,sysadmin@plurisinc.com,S834EA785951,999
1,Pluris Marketing,Adam Estabrook,sysadmin@plurisinc.com,S0A7A3C0AADD,999
2,Peterborough Regional College,Pete Griffiths,network.services@peterborough.ac.uk,S2E9CD0F5945,999
3,MIAC,Robert N Husted,bob.husted@miacanalytics.com,S04E031E11C4,999
4,PVA,Lezlie Zupan,lesliez@pva.org,S0F8199A8494,999
5,Deceuninck NV,Tec support,tec-support@deceuninck.com,S6FDB1355025,999
6,Migros ZÃ¼rich,Richard Huber,richard.huber@realstuff.ch,SFEA98D9E199,999
7,"Trepp, LLC",David Baboo,david@trepp.com,S3A4A4356983,1200
8,Summit IT solutions Pvt Ltd.,Vasudev Nayak,vasudev.nayak@symphonysummit.com,S8ED72E60F21,1200
9,Aquent,Robert Stretz,eno@aquent.com,SC28FF262A2F,999
10,Brother International (Aust) Pty Ltd,Terence Yuen,terence.yuen@brother.com.au,S04358CEC03D,999
11,Barrachd Limited,clark wilson,clark.wilson@barrachd.com,S34B6A999D68,999
12,Barrachd Limited,clark wilson,clark.wilson@barrachd.com,S1A1801ED8D4,999
13,Taylor Corporation,Deven McVenes,djmcvenes@taylorcorp.com,S871C0469856,999
14,Banco Popular EspaÃ±ol S.A.,Marcos Hernandez,mhernandezg@bancopopular.es,S71C44EC24FC,999
15,All for One Steeb AG,Cindy Schneider,Zentraleinkauf@all-for-one.com,S691B9E604B3,999
16,Traquer Oy,Sami Maenpaa,sami.maenpaa@traquer.fi,S88AD43AF238,999
17,COOP Genossenschaft,Christian Mueller,sysmgmt@coop.ch,S2A74A816D6C,999
18,Migros ZÃ¼rich,Richard Huber,richard.huber@realstuff.ch,S2629B8B4771,999
19,G-C Partners,David Cowen,dcowen@g-cpartners.com,SB6FD367F90E,999
20,Merck,Daniel Arnost,daniel.arnost@merck.com,SECEA3B6876E,1200
21,Princeton University,Steven Niedzwiecki,steven@princeton.edu,S2F480BB1323,999
22,NCCW,Theo Ariens,service@nccw.nl,SB723E477648,999
23,NCCW,Theo Ariens,service@nccw.nl,S912A239431A,999
24,NCCW,Theo Ariens,service@nccw.nl,SE5EED5F7E75,999
25,Macmillan Publishers,Mariano Gardellini,m.gardellini@us.nature.com,SC88F4980F42,999
26,Macmillan Publishers,Mariano Gardellini,m.gardellini@us.nature.com,S357320B71B8,999
27,Overnite Software Inc.,Ernest Bowie,itsupport@overnitecbt.com,S22D9DA46322,999
28,Dbvisit Software Limited,Anton Els,anton.els@dbvisit.com,S092FCDE35E8,999
29,Data Conversion Laboratory Inc.,Judy Gross,mikegross@dclab.com,SEC66BEC3E9B,999
30,Michelin,William Rhoten,william.rhoten@michelin.com,S7B17D90D391,999
31,Skagit Valley College,Teresa Miller,tmiller@skagit.edu,SCF07C578484,999
32,Parker-Hannifin Corporation,Robert Deragisch,bderagisch@parker.com,S0EA8CAEFFEE,999
33,Fides Management,Maarten Van Laere,maarten.vanlaere@fides-management.com,S3DCFE3111D1,999
34,Fiserv,Jerry Rabenberg,jerry.rabenberg@fiserv.com,S4DBA544FB5C,999
35,Samba Plans,Pat Peel,ppeel@sambaplans.com,S4902BEC4DDB,999
36,Grain Corp.,Klaus Brinkmeyer,sjohnston@graincorp.com.au,S9BB837EEB22,999
37,Inasys GmbH,Suzanne Johnston,Klaus.Brinkmeyer@inasys.de,S30D18781CB7,999
38,Morneau Shepell ltd,Morneau Shepell,itpurchases@morneaushepell.com,S06EAB6DD175,999
39,Morneau Shepell ltd,Morneau Shepell,itpurchases@morneaushepell.com,SCF9093DF162,999
40,Morneau Shepell ltd,Morneau Shepell,itpurchases@morneaushepell.com,S9033A83CB06,999
41,FibreBlu Technology Inc.,Kirk Pollock,fibreblu@yahoo.ca,SBED462011AB,399
42,"Levi, Ray & Shoup, Inc.",John Runions,john.runions@lrs.com,S696C2CA2DD6,999
43,NCCW,Theo Ariens,service@nccw.nl,SF5C6F3FD6AD,999
44,Green River College,Rhonda Daulton,itpurchasing@greenriver.edu,S918C5218970,999

In [57]:
pd.pivot_table(df4, index=['Company Name', 'Cardholder Name', 'Serial #'])

                                                                       Amount
Company Name                         Cardholder Name    Serial #
All for One Steeb AG                 Cindy Schneider    S691B9E604B3      999
Aquent                               Robert Stretz      SC28FF262A2F      999
Banco Popular EspaÃ±ol S.A.           Marcos Hernandez   S71C44EC24FC      999
Barrachd Limited                     clark wilson       S1A1801ED8D4      999
                                                        S34B6A999D68      999
Brother International (Aust) Pty Ltd Terence Yuen       S04358CEC03D      999
COOP Genossenschaft                  Christian Mueller  S2A74A816D6C      999
Data Conversion Laboratory Inc.      Judy Gross         SEC66BEC3E9B      999
Dbvisit Software Limited             Anton Els          S092FCDE35E8      999
Deceuninck NV                        Tec support        S6FDB1355025      999
FibreBlu Technology Inc.             Kirk Pollock       SBED462011AB      399
Fides Management                     Maarten Van Laere  S3DCFE3111D1      999
Fiserv                               Jerry Rabenberg    S4DBA544FB5C      999
G-C Partners                         David Cowen        SB6FD367F90E      999
Grain Corp.                          Klaus Brinkmeyer   S9BB837EEB22      999
Green River College                  Rhonda Daulton     Â S918C5218970     999
Inasys GmbH                          Suzanne Johnston   S30D18781CB7      999
Levi, Ray & Shoup, Inc.              John Runions       S696C2CA2DD6      999
MIAC                                 Robert N Husted    S04E031E11C4      999
Macmillan Publishers                 Mariano Gardellini S357320B71B8      999
                                                        SC88F4980F42      999
Merck                                Daniel Arnost      SECEA3B6876E     1200
Michelin                             William Rhoten     S7B17D90D391      999
Migros ZÃ¼rich                        Richard Huber      S2629B8B4771      999
                                                        SFEA98D9E199      999
Morneau Shepell ltd                  Morneau Shepell    S06EAB6DD175      999
                                                        S9033A83CB06      999
                                                        SCF9093DF162      999
NCCW                                 Theo Ariens        S912A239431A      999
                                                        SB723E477648      999
                                                        SE5EED5F7E75      999
                                                        SF5C6F3FD6AD      999
Overnite Software Inc.               Ernest Bowie       S22D9DA46322      999
PVA                                  Lezlie Zupan       S0F8199A8494      999
Parker-Hannifin Corporation          Robert Deragisch   S0EA8CAEFFEE      999
Peterborough Regional College        Pete Griffiths     S2E9CD0F5945      999
Pluris Marketing                     Adam Estabrook     S0A7A3C0AADD      999
                                                        S834EA785951      999
Princeton University                 Steven Niedzwiecki S2F480BB1323      999
Samba Plans                          Pat Peel           S4902BEC4DDB      999
Skagit Valley College                Teresa Miller      SCF07C578484      999
Summit IT solutions Pvt Ltd.         Vasudev Nayak      S8ED72E60F21     1200
Taylor Corporation                   Deven McVenes      S871C0469856      999
Traquer Oy                           Sami Maenpaa       S88AD43AF238      999
Trepp, LLC                           David Baboo        S3A4A4356983     1200

In [76]:
df5 = pd.DataFrame(df4.stack())
df5

                                                      0
0  Company Name                        Pluris Marketing
   Cardholder Name                       Adam Estabrook
   E-mail                        sysadmin@plurisinc.com
   Serial #                                S834EA785951
   Amount                                           999
1  Company Name                        Pluris Marketing
   Cardholder Name                       Adam Estabrook
   E-mail                        sysadmin@plurisinc.com
   Serial #                                S0A7A3C0AADD
   Amount                                           999
2  Company Name           Peterborough Regional College
   Cardholder Name                       Pete Griffiths
   E-mail           network.services@peterborough.ac.uk
   Serial #                                S2E9CD0F5945
   Amount                                           999
3  Company Name                                    MIAC
   Cardholder Name                      Robert N Husted
   E-mail                  bob.husted@miacanalytics.com
   Serial #                                S04E031E11C4
   Amount                                           999
4  Company Name                                     PVA
   Cardholder Name                         Lezlie Zupan
   E-mail                               lesliez@pva.org
   Serial #                                S0F8199A8494
   Amount                                           999
5  Company Name                           Deceuninck NV
   Cardholder Name                          Tec support
   E-mail                    tec-support@deceuninck.com
   Serial #                                S6FDB1355025
   Amount                                           999
...                                                 ...
39 Company Name                     Morneau Shepell ltd
   Cardholder Name                      Morneau Shepell
   E-mail                itpurchases@morneaushepell.com
   Serial #                                SCF9093DF162
   Amount                                           999
40 Company Name                     Morneau Shepell ltd
   Cardholder Name                      Morneau Shepell
   E-mail                itpurchases@morneaushepell.com
   Serial #                                S9033A83CB06
   Amount                                           999
41 Company Name                FibreBlu Technology Inc.
   Cardholder Name                         Kirk Pollock
   E-mail                             fibreblu@yahoo.ca
   Serial #                                SBED462011AB
   Amount                                           399
42 Company Name                 Levi, Ray & Shoup, Inc.
   Cardholder Name                         John Runions
   E-mail                          john.runions@lrs.com
   Serial #                                S696C2CA2DD6
   Amount                                           999
43 Company Name                                    NCCW
   Cardholder Name                          Theo Ariens
   E-mail                               service@nccw.nl
   Serial #                                SF5C6F3FD6AD
   Amount                                           999
44 Company Name                     Green River College
   Cardholder Name                       Rhonda Daulton
   E-mail                   itpurchasing@greenriver.edu
   Serial #                               Â S918C5218970
   Amount                                           999

[225 rows x 1 columns]

In [92]:

be = pd.read_csv('data/be_subscribers_auto_recurring.csv', index_col=['Company Name', 'Cardholder Name', 'Serial #'])
be2 = be[['Invoice', 'Service Enabled', 'Last Charge Date',
       'Nex Renewal Date',  
       'Amount', 'E-mail', 'AS Order #', 'Login ID (SSO ID)']]
be2.head()

                                                                                                   Invoice  \
Company Name                  Cardholder Name Serial #
Pluris Marketing              Adam Estabrook  S834EA785951    12 Month Service ActivePerl Business Edition
                                              S0A7A3C0AADD    12 Month Service ActivePerl Business Edition
Peterborough Regional College Pete Griffiths  S2E9CD0F5945    12 Month Service ActivePerl Business Edition
MIAC                          Robert N Husted S04E031E11C4  12 Month Service ActivePython Business Edition
PVA                           Lezlie Zupan    S0F8199A8494    12 Month Service ActivePerl Business Edition

                                                                          Service Enabled  \
Company Name                  Cardholder Name Serial #
Pluris Marketing              Adam Estabrook  S834EA785951    ActivePerl Business Edition
                                              S0A7A3C0AADD    ActivePerl Business Edition
Peterborough Regional College Pete Griffiths  S2E9CD0F5945    ActivePerl Business Edition
MIAC                          Robert N Husted S04E031E11C4  ActivePython Business Edition
PVA                           Lezlie Zupan    S0F8199A8494    ActivePerl Business Edition

                                                           Last Charge Date  \
Company Name                  Cardholder Name Serial #
Pluris Marketing              Adam Estabrook  S834EA785951         9/5/2017
                                              S0A7A3C0AADD         9/5/2017
Peterborough Regional College Pete Griffiths  S2E9CD0F5945        9/11/2017
MIAC                          Robert N Husted S04E031E11C4        9/27/2017
PVA                           Lezlie Zupan    S0F8199A8494        10/4/2017

                                                           Nex Renewal Date  \
Company Name                  Cardholder Name Serial #
Pluris Marketing              Adam Estabrook  S834EA785951         9/5/2018
                                              S0A7A3C0AADD         9/5/2018
Peterborough Regional College Pete Griffiths  S2E9CD0F5945        9/11/2018
MIAC                          Robert N Husted S04E031E11C4        9/27/2018
PVA                           Lezlie Zupan    S0F8199A8494        10/4/2018

                                                            Amount  \
Company Name                  Cardholder Name Serial #
Pluris Marketing              Adam Estabrook  S834EA785951     999
                                              S0A7A3C0AADD     999
Peterborough Regional College Pete Griffiths  S2E9CD0F5945     999
MIAC                          Robert N Husted S04E031E11C4     999
PVA                           Lezlie Zupan    S0F8199A8494     999

                                                                                         E-mail  \
Company Name                  Cardholder Name Serial #
Pluris Marketing              Adam Estabrook  S834EA785951               sysadmin@plurisinc.com
                                              S0A7A3C0AADD               sysadmin@plurisinc.com
Peterborough Regional College Pete Griffiths  S2E9CD0F5945  network.services@peterborough.ac.uk
MIAC                          Robert N Husted S04E031E11C4         bob.husted@miacanalytics.com
PVA                           Lezlie Zupan    S0F8199A8494                      lesliez@pva.org

                                                            AS Order #  \
Company Name                  Cardholder Name Serial #
Pluris Marketing              Adam Estabrook  S834EA785951      601426
                                              S0A7A3C0AADD      601426
Peterborough Regional College Pete Griffiths  S2E9CD0F5945      601465
MIAC                          Robert N Husted S04E031E11C4      601806
PVA                           Lezlie Zupan    S0F8199A8494      601955

                                                            Login ID (SSO ID)
Company Name                  Cardholder Name Serial #
Pluris Marketing              Adam Estabrook  S834EA785951            4252395
                                              S0A7A3C0AADD            4252395
Peterborough Regional College Pete Griffiths  S2E9CD0F5945             905827
MIAC                          Robert N Husted S04E031E11C4            4215377
PVA                           Lezlie Zupan    S0F8199A8494            4234590